package es.upv.com.aenaApp.controller;

import java.io.IOException;

import javafx.application.Platform;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;


public class mainSceneController {
	String css = "es/upv/com/aenaApp/view/application.css";
	String airports = "airportScene.fxml";
	String flightStatics = "StaticsScene.fxml";
	
	Dialogs framework= new Dialogs();
	

	@FXML
	public void airportsWindow(ActionEvent event) throws IOException {
		
		framework.loadScene(airports,event);

	}

	// Event Listener on Button.onAction
	@FXML
	public void fligthsWindow(ActionEvent event) throws IOException {
		// TODO Autogenerated
		framework.loadScene(flightStatics, event);
		
	}

	// Event Listener on Button.onAction
	@FXML
	public void salir(ActionEvent event) {
		// TODO Autogenerated
		Platform.exit();
	}
}